---
kind: pipeline
type: docker
name: build

steps:
  - name: notify-start
    image: pztrn/discordrone
    settings:
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_secret
      message: 'Starting building **{{repo.name}}#{{build.number}}@{{build.commit}}** @ {{datetime build.started "02-Jan-2006 15:04:05 MST" "Asia/Yekaterinburg"}} (See {{build.link}} for logs).'

  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_user
      password:
        from_secret: dockerhub_password
      repo: pztrn/taskd
      auto_tag: true

  - name: notify-end
    when:
      status:
        - success
        - failure
    image: pztrn/discordrone
    settings:
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_secret
      message: "
        {{#success build.status}}
        **{{repo.name}}#{{build.number}}@{{build.commit}}** deployed.
        {{ else }}
        **{{repo.name}}#{{build.number}}@{{build.commit}}** failed. See {{build.link}}.
        {{/success}}"
